version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
  worker:
    build: .
    command: celery worker -A example -l info
    volumes:
      - .:/code
    links:
      - db
      - rabbitmq
      - redis
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    volumes:
      - webpack:/webpack/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./node_modules:/webpack/node_modules
      - ./assets/bundles:/webpack/assets/bundles
    ports:
      - "8000:8000"
    links:
      - db
      - rabbitmq
      - redis
volumes:
  webpack:
    driver: local
